name: HREMGromacs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - plumed
  - parmed
  - pip:
    - 'git+https://github.com/MauriceKarrenbrock/FSDAMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonAuxiliaryFunctions'
